flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- SHA-1.6.4.2
- async-2.1.1.1
- attoparsec-0.13.1.0
- base64-bytestring-1.0.0.1
- binary-0.8.5.1
- blaze-builder-0.4.0.2
- Cabal-1.24.2.0
- case-insensitive-1.2.0.10
- digest-0.0.1.2
- directory-1.3.1.1
- entropy-0.3.8
- exceptions-0.8.3
- fail-4.9.0.0
- fsnotify-0.2.1
- hashable-1.2.6.1
- hinotify-0.3.9
- integer-logarithms-1.0.2
- lifted-base-0.2.3.11
- mmorph-1.0.9
- monad-control-1.0.2.1
- mtl-2.2.1
- network-2.6.3.2
- primitive-0.6.2.0
- process-1.4.3.0
- random-1.1
- resourcet-1.1.9
- scientific-0.3.5.1
- semigroups-0.18.3
- split-0.2.3.2
- stm-2.4.4.1
- streaming-0.1.4.5
- streaming-bytestring-0.1.4.6
- streaming-commons-0.1.18
- tagged-0.8.5
- text-1.2.2.2
- transformers-0.5.4.0
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unix-2.7.2.1
- unix-compat-0.4.3.1
- unordered-containers-0.2.8.0
- websockets-0.12.0.0
- zlib-0.6.1.2
resolver: ghc-7.10
