flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- Cabal-1.24.2.0
- SHA-1.6.4.2
- asn1-encoding-0.9.5
- asn1-parse-0.9.4
- asn1-types-0.3.2
- async-2.1.1.1
- attoparsec-0.13.1.0
- base64-bytestring-1.0.0.1
- binary-0.8.5.1
- blaze-builder-0.4.0.2
- byteable-0.1.1
- case-insensitive-1.2.0.10
- cereal-0.5.4.0
- connection-0.2.8
- cryptonite-0.24
- data-default-class-0.1.2.0
- digest-0.0.1.2
- directory-1.3.1.1
- entropy-0.3.8
- fail-4.9.0.0
- foundation-0.0.13
- hashable-1.2.6.1
- hourglass-0.2.10
- integer-logarithms-1.0.2
- memory-0.14.6
- mtl-2.2.1
- network-2.6.3.2
- pem-0.2.2
- primitive-0.6.2.0
- process-1.4.3.0
- random-1.1
- scientific-0.3.5.1
- semigroups-0.18.3
- socks-0.5.5
- split-0.2.3.2
- stm-2.4.4.1
- streaming-commons-0.1.18
- tagged-0.8.5
- text-1.2.2.2
- tls-1.3.11
- transformers-0.5.4.0
- transformers-compat-0.5.1.4
- unix-2.7.2.1
- unordered-containers-0.2.8.0
- websockets-0.11.2.0
- wuss-1.1.4
- x509-1.6.5
- x509-store-1.6.2
- x509-system-1.6.4
- x509-validation-1.6.5
- zlib-0.6.1.2
resolver: ghc-7.10
